# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KAOS
description: The KAOS roleplaying game system
url: "https://moccalotto.github.io" # the base hostname & protocol for your site
baseurl: "/kaos"                    # the subpath of your site, e.g. /blog

author: Moccalotto
email: moccalotto+kaos@gmail.com
twitter_username: moccalotto
github_username:  moccalotto
# permalink: pretty

# Build settings
markdown: kramdown

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

collections:
  brainstorms:
    output: true
    permalink: /:collection/:path/

  rulebook:
    output: true
    permalink: /:collection/:path/

  campaign:
    output: true
    permalink: /:collection/:path/

  places:
    output: true
    permalink: /:collection/:path/

  monsters:
    output: true
    permalink: /:collection/:path/
