= Showdown
Kim Ravn Hansen <kim@krhit.com>
v0.1 2019-01-06

:sectanchors:
:sectlinks:
:toc:

The year is 2099 and the world is even stranger than many would think possible.

In 2020 a computer virus emerged and became semi-sapient and caused many
computers connected to the internet to crash. This virus left messages on the
crashed computers, wherein it referred to itself as Digital Chaos. After a few
months of hard work, the virus was destroyed.

In 2023 the discovery of a "magic wand" in the Gobi desert caused what we now
know as the <<magical-emergence, Magical Emergence>>, followed by the
<<epocalypse>>.

In 2027 it was discovered that computers and networks would not be infected by
Digital Chaos if they were 6 or more meters underground.

In 2028 a First Nation shaman, Hank Whiteknife suddenly discovered that prayers
and rituals to to the Inuit deities were answered. He became the first True
Shaman, and he immediately asked the gods and the spirits to save the land.
This caused an event much of the North American content to become as lush and
clean as it was a thousand years ago. In fact, the gods did not stop there; the
new plat life was so persistent that only large towns and cities could fend it
off. Trees sprouted everywhere, not being hindered by roads, pavements, or
parking lots.  The oceans also got cleaner, bringing back much of the marine
life that had been lost throughout the years of constant pollution.  In the
following years, this also happened on the other continents, causing the entire
globe to become much cleaner and healthier, and even causing the climate to
become cooler and the weather more stable.

In 2031 the FoxWing corporation was granted status as a sovereign territory in
the US in exchange for large cash amounts paid to both the state of Newark as
well as the federal government. FoxWing became known as the first Sovereign
Corporation, popularly known as a <<mega-corps,Mega Corp>>. Many more of these
Mega Corps were to follow.

In 2038 a family of Dire Boar was found in a forest in Saxony, Germany. This
was the first discovery of meta-animals. Many more were to come in the coming
years.

In 2040 the first airline opened using airships. They used one blimp for local
routes in the US, and a zeppelin to ferry people across the Atlantic ocean.
Air travel was extremely expensive since oil and gas were still at a premium.
Blimps and dirigibles could operate partially on solar energy, which made them
much cheaper and more efficient.

In 2041 the poor living conditions and the religious issues with the new
"mutant" races caused violent civil riots and protests, almost on par with a
civil war.

In 2042 the first elemental minerals were discovered. These minerals had unique
properties that made them very hard, very tough very tensile, as well as
corrosion- and radiation resistant. It took almost 10 years of intense research
for scientists to figure out how to refine and work the minerals at reasonable
costs.

In 2044 the Great European Racial Conflict took place. A large part of the
populous of Europe was scared of (and angry with) the new "mutant babies" and
what they represented. Almost 1 in 3 children under the age of 6 were now
"mutated" in some way. The problem was exacerbated since not many politicians
had children under the age of 6, and so could not directly relate to the
problem. These problems persisted for almost three years before the UN added
articles to the declaration of human rights to include »any biological,
sapient, and enlightened being«. As a result of this, the term _enlightened_
was used to encapsulate all of the new races that had been born to human
parents.

In 2045 the American Racial Conflict came to a close, splitting the US in two,
The bible belt became its own nation called The Sanctified States of America
(SSA). The SSA became a theocratic nation with a large military. Only a few
choice mega corps were allowed on SSA land, and some Mega Corps were forcibly
evicted. The states that are now part of the SSA: Alabama, Arkansas, Georgia,
Kentucky, Louisiana, Mississippi, Missouri, North Carolina, Ohio, Oklahoma,
South Carolina, South Dakota, Tennessee, Texas, Virginia, and West Virginia.
The remaining states of the US chose the name Allied States of North America.

In the 2051 the world's first _cybertown_ was opened in the city of Boston.
Cybertowns are underground areas where you can use any IT product you want
without the risk of it being infected by Digital Chaos. These cybertowns
became hugely popular, and many were built all around the globe.

In 2059 the first <<agents,Agent>> computer was released.

[#magical-emergence]
== Magical Emergence

An artifact, later known as the »magic wand« was discovered in a copper mine in
the Gobi desert in southern Mongolia. The artifact,  was a 50.3 centimeter long
rod made of a metal that resembled titanium, but it did not have the same
properties (scientists now speculate that the material is of a supreme kind of
elemental mineral). It was handed over to a British university for study.
After a few weeks of of being studied, the artifact suddenly gave off a bright
light and a high dose of ionizing radiation. The radiation could be measured
instantly all around the globe. In fact, many people think the effect broke the
speed of light. Many nations went into high alert and the world held its breath
for long hours until it was clear that no nation had attacked another. Even
though the radiation could be measured all around the world, and many people
reported seeing strange lights in the sky, no living beings got sick. At least
not right away. Rather, it led to what is now known as <<magical-emergence>>.
But the calm did not last long. Only about 36 hours after the radiation event,
the Digital Chaos virus woke up, this time truly sapient, and still highly
malicious, causing the disaster known as the <<epocalypse>>.

[#epocalypse]
=== The Epocalypse

The magical emergence also revived the Digital Chaos virus and gave it powerful
magical abilities. It became able to infect and control any digital device with
a radio receiver or any computer that was not shielded against radio waves, and
infected computers could infect other computers if they were networked
together. And so the world quickly collapsed into chaos and mayhem as power
plants, airplanes, satellites, cars, ships, factories, farms and hospitals
failed catastrophically as their computer systems were infected with digital
chaos.  This demonic computer virus controlled the devices in such a way as to
cause as much mayhem, destruction and death as possible. Millions died almost
instantly, and millions more in the following days as the hospitals were no
longer able to function efficiently.

In this new world, there are no more Mobile Phones, GPS, WiFi, Bluetooth,
Electronic payment, Controllable drones, Internet at home and Digital TVs.


[#new-world]
== The new World

[#enlightened]
=== Enlightened Races

* Gnome
* Elemental
* Beastkin
** Minotaur
** Wolfman
** Lizardman

=== Meta animals

==== Dire Creatures


=== The Wild

Due to Druidic magic, forests and jungles have taken over much of the land.

==== Minerals and fossil fuels

Fossil fuels are very expensive because extraction is difficult without
computers.  It does not help that the Druidic magic has made it much more
difficult to access mines.


[#mega-corps]
=== Mega Corps

The first company to become a Sovereign Company (Mega Corp) was FoxWing, when
they exploited the US governments acute need for a cash infusion. In the US, a
Sovereign Company is effectively a state or territory. This means that the
employees who live on the corporate campus only pay federal tax, and that the
state does not need to provide any services (utilities, school, social
services, etc.) to those employees.

FoxWing also made a similar deal in Mexico in 2042. Many other companies
followed suit in the following years.  By 2060, more than 500 sovereign company
territories were registered all over the globe.

Not all of these territories function the same way. In some countries,
companies can be granted the same status as a foreign embassy, in others they
can be given status as small counties or municipalities.

The Philippines sold off a number of small islands to various companies,
completely surrendering them to those corporations such that they became
sovereign pseudo-nations with their own passports, etc. These »Corponations«
are not UN members, nor do they have any formal army. However they do patrol
their borders with security personnel.

This led to mega corps having vast and widespread power, making it increasingly
difficult for independent startups to succeed. Moreover, persons without
affiliation with a mega corp had harder times getting good living conditions
and a decent quality of life.

However, many economists have noted that the selling of land to private companies
was the main driver in recovering the global economy after the Epocalypse.

[#technology]
=== Technology


[#communication]
==== Communication

§§§§ Data Cables must reside at least 6 meters below ground in order to
facilitate digital data communication. Cables must be inspected often in order
to ensure that they have not been compromised (by removing soil above them).



[#agents]
==== Agents

In 2059 the company Cyberstorm released »Agent«, a small, computer that could
be used above ground without risk of being infected by Digital Chaos. The agent
is a shielded in a case with layers of lead, gold, and elemental minerals. The
first agents were quite large, taking up about 4 x 10 x 10 centimeters, but the
later models take up about 2 x 5 x 10 centemeters.

An agent is only active when it is inserted into an agent-enabled device. You
can connect the agent to a so-called agent-terminal (essentially a touchscreen and
possibly a keyboard), and use that to interact with the agent. You can also
plug the agent into an agent-enabled car, and let the agent guide you, or even
drive the vehicle for you. Agent-enabled devices are completely dumb and have no
processing nodes to speak of; they require the Agent to work.

The agent is an "AI" that makes it much easier to use the device on which it
runs. You can give it verbal instructions and it can essentially make the
device do stuff that previously required a multitude of custom software.  For
instance, you can ask your agent to solve complex equations, to set an alarm
10 minutes before the next full moon rises, or to guide you across town.

[#cybertowns]
==== Cybertowns

§§§ Large underground areas where you can use your IT equipment without any
issues. 
