= Showdown
Kim Ravn Hansen <kim@krhit.com>
v0.1 2019-01-06

:toc:

The year is 2099 and the world is even stranger than many would think possible.

In 2020 a computer virus emerged and became semi-sapient and caused many
computers connected to the internet to crash. This virus left messages on the
crashed computers, wherein it referred to itself as Digital Chaos. After a few
months of hard work, the virus was destroyed.

In 2022 FoxWing, a large corporation, entered into formal negotiations with the
state of Newark and the federal government of the USA about becoming a
sovereign entity, seeking to have the same status as a state or territory.

In 2023 an artifact was discovered in a copper mine in the Gobi desert in
southern Mongolia. The artifact, now known as the "magic wand" was a 50
centimeter long rod made of a metal that resembled titanium, but it did not
have the same properties. It was handed over to a British university for study.
After a few weeks of of being studied, the artifact suddenly gave off a bright
light and a high dose of ionizing radiation. The radiation could be measured
instantly all around the globe. In fact, many people think the effect broke the
speed of light. Many nations went into high alert and the world held its breath
for long hours until it was clear that no nation had attacked another. Even
though the radiation could be measured all around the world, and many people
reported seeing strange lights in the sky, no living beings got sick. At least
not right away. Rather, it led to what is now known as <<Magical Emergence>>.
But the calm did not last long. Only about 36 hours after the radiation event,
the Digital Chaos virus woke up, this time truly sapient, and still highly
malicious, causing the disaster known as <<The Epocalypse>>.

In 2027 it was discovered that computers and networks would not be infected by
Digital Chaos if they were 5 or more meters underground.

In 2028 a First Nation shaman, Hank Whiteknife suddenly discovered that prayers
and rituals to to the Inuit deities were answered. He became the first True
Shaman, and he immediately asked the gods and the spirits to save the land.
This caused an event much of the North American content to become as lush and
clean as it was a thousand years ago. In fact, the gods did not stop there; the
new plat life was so persistent that only large towns and cities could fend it
off. Trees sprouted everywhere, not being hindered by roads, pavements, or
parking lots.  The oceans also got cleaner, bringing back much of the marine
life that had been lost throughout the years of constant pollution.  In the
following years, this also happened on the other continents, causing the entire
globe to become much cleaner and healthier, and even causing the climate to
become cooler and the weather more stable.

In 2038 a family of Dire Boar was found in a forest in Saxony, Germany. This
was the first discovery of meta-animals. Many more were to come in the coming
years.

In 2040 the FoxWing corporation was granted status as a sovereign territory in
the US in exchange for large cash amounts paid to both the state of Newark as
well as the federal government. FoxWing became known as the first Sovereign
Corporation, popularly known as a "Mega Corp" or "Power Corp". Many more of
these Mega Corps were to follow.

In 2040 the first airline opened using airships. They used one blimp for local
routes in the US, and a zeppelin to ferry people across the Atlantic ocean.
Air travel was extremely expensive since oil and gas were still at a premium.
Blimps and dirigibles could operate on partial electrical energy, which made 
them much cheaper.

In 2041 the poor living conditions and the religious issues with the new
»mutant« races caused violent civil riots and protests, almost on par with a
civil war.

In 2042 the first elemental minerals were discovered. These minerals had unique
properties that made them very hard, very tough very tensile, as well as
corrosion- and radiation resistant. It took almost 10 years of intense research
for scientists to figure out how to refine and work the minerals at reasonable
costs.

In 2042 the Great European Racial Conflict took place. A large part of the
populous of Europe was scared of (and angry with) the new "mutant babies" and
what they represented. Almost 1 in 3 children under the age of 6 were now
"mutated" in some way. The problem was exacerbated since not many politicians
had children under the age of 6, and so could not directly relate to the
problem. These problems persisted for almost three years before the UN added
articles to the declaration of human rights to include sapient biological
beings that could trace their lineage back to 

In 2045 the American Racial Conflict came to a close, splitting the US in two,
The bible belt became its own nation called The Sanctified States of America
(SSA). The SSA became a Theocratic police state with a large military.  Only a
few choice mega corps were allowed on SSA land, and some Mega Corps were
forcable evicted. The states that are now part of the SSA: Alabama, Louisiana,
Tennessee, Mississippi, Oklahoma, Texas, Kentucky, Arkansas, West Virginia,
South Carolina, Georgia, North Carolina, Missouri, Ohio, Virginia, and South
Dakota. In order to avoid further conflict, the remaining states of the US
chose the name Allied States of North America.

In the 2050s the world's first DC-safe udnerground area to the public in
Boston. This allowed the use of wireless networks, PDAs, tablets, laptops, etc.
This area was called the Boston Cybertown.

In 2059 the first <<Agents,Agent>> computer was released.

In 2060 the 

== Magical Emergence

Many of the babies conceived after the day of magical emergence were more than
just human. Some had strange abilities we now know as magic, and some had
mutations that we know as classify as elementals, beastkin, and gnomes.

=== The Epocalypse

The magical emergence also revived the Digital Chaos virus and gave it powerful
magical abilities. It became able to infect and control any digital device with
a radio receiver or any computer that was not shielded against radio waves, and
infected computers could infect other computers if they were networked
together. And so the world quickly collapsed into chaos and mayhem as power
plants, airplanes, satellites, cars, ships, factories, farms and hospitals
failed catastrophically as their computer systems were infected with digital
chaos.  This demonic computer virus controlled the devices in such a way as to
cause as much mayhem, destruction and death as possible. Millions died almost
instantly, and millions more in the following days as the hospitals were no
longer able to function efficiently.

In this new world, there are no more Mobile Phones, GPS, WiFi, Bluetooth,
Electronic payment, Controllable drones, Internet at home and Digital TVs.

==== But the world recovered

In the aftermath of the Epocalypse, humanity started to very slowly rebuild
their infrastructure, using technology from the middle of the 20th century,
completely avoiding the use of computers.

It was discovered that computers and networks would not be infected if they
were located completely underground with at least 5 meters of rock or soil
above them.  This led to the construction of large underground facilities that
housed any vital services that required computing power.

Land line phones have also been replaced with technology from the 1960s where a
human switchboard operator will redirect your call.

There are, however, personal computers, wrist computers, self-driving cars, and
semi-autonomous drones. 


== The new World

=== New Humans

New human races.


=== Meta animals

Blah.


=== The Wild

Due to Druidic magic, forests and jungles have taken over much of the land.



=== Various

==== Minerals and fossil fuels

Fossil fuels are very expensive because extraction is difficult without
computers.  It does not help that the Druidic magic has made it much more
difficult to access mines.



=== Mega Corps

The first company to become a Sovereign Company (Mega Corp) was FoxWing, when
they exploited the US governments acute need for a cash infusion. In the US, a
Sovereign Company is effectively a state or territory. This means that the
employees who live on the corporate campus only pay federal tax, and that the
state does not need to provide any services (utilities, school, social
services, etc.) to those employees.

FoxWing also made a similar deal in Mexico in 2042. Many other companies
followed suit in the following years.  By 2060, more than 500 sovereign company
territories were registered all over the globe.

Not all of these territories function the same way. In some countries,
companies can be granted the same status as a foreign embassy, in others they
can be given status as small counties or municipalities.

The Philippines sold off a number of small islands to various companies,
completely surrendering them to those corporations such that they became
sovereign nations with their own passports, etc. These "Corponations" are not
UN members, nor do they have any formal army. However they do patrol their
borders with security personnel.

This led to mega corps having vast and widespread power, making it increasingly
difficult for independent startups to succeed.

However, many economists have noted that the selling of land to private companies
was the main driver in recovering the global economy after the Epocalypse.


=== Agents

In 2059 the company Cyberstorm released »Agent«, a small, computer that could
be used above ground without risk of being infected by Digital Chaos. The agent
is a shielded in a case with layers of lead, gold, and elemental minerals. The
first agents were quite large, taking up about 4 x 10 x 10 centimeters, but the
later models take up about 2 x 5 x 10 centemeters.

An agent is only active when it is inserted into an agent-enabled device. You
can connect the agent to a so-called agent-terminal (essentially a touchscreen and
possibly a keyboard), and use that to interact with the agent. You can also
plug the agent into an agent-enabled car, and let the agent guide you, or even
drive the vehicle for you. Agent-enabled devices are completely dumb and have no
processing nodes to speak of; they require the Agent to work.

The agent is an "AI" that makes it much easier to use the device on which it
runs. You can give it verbal instructions and it can essentially make the
device do stuff that previously required a multitude of custom software.  For
instance, you can ask your agent to solve complex equations, to set an alarm
10 minutes before the next full moon rises, or to guide you across town.
